services:
  # Backend API Service
  - type: web
    name: doggyloops-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: dpg-d1atajre5dus73e1d750-a.frankfurt-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: luis_cabrera
      - key: DB_PASSWORD
        sync: iV5iw7QIG6zmJJRL6EbOlWEZYsYZQaT0
      - key: DB_NAME
        value: portfolio_db_9tib
      - key: DB_SSL
        value: true
      - key: PORT
        value: 3001
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: doggyloops-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://doggyloops-backend.onrender.com
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
